Server/tasks
shubham-cpp/astro-project-manager pull request #3
Opened 2023-03-01 11:59 UTC by isandeepkadam

2023-03-04 04:00 UTC, shubham-cpp requested changes
### Changes in `controllers/Task.ts`:
- [ ] Complete the CRUD operations.(Update/Delete)
- [ ] Find Tasks assigned to/by User(createdBy,current owner)

### Changes in `models/Task.ts`:
- [x] Rename `days` -> `daysAllocated` (Having descriptive names help in writing less comments/docs)
- [x] Rename `project` -> `projectId` (All the ObjectIds should have a suffix Id)
- [ ] We might want to make some fields optional( like daysAllocated,etc. I'll explain this in next call)

2023-03-11 13:33 UTC, shubham-cpp commented on server/src/models/Task.ts
> +    type: Number,
projectId should be required

2023-03-11 13:33 UTC, shubham-cpp commented on server/src/controllers/Task.ts
> +      .then(
if we're already using try/catch block then why not use await instead of promise chaining(`.then()`)

2023-03-11 13:33 UTC, shubham-cpp commented on server/src/controllers/Task.ts
> +    const user = await User.findOne({ refreshToken });
refreshToken is not the id, we need to `jwt.decode` to extract the id from token

2023-03-11 13:33 UTC, shubham-cpp commented on server/src/controllers/Task.ts
> +        .then(
same, if we're using try/catch block them just use `const task = await Task.findOne({..})` instead of promise chaining

2023-03-11 13:33 UTC, shubham-cpp commented on server/src/controllers/Task.ts
> +        refreshToken,
We dont need `refreshToken` when creating a Task. We dont save refreshToken in mongodb

2023-03-11 13:33 UTC, shubham-cpp commented on server/src/controllers/Task.ts
> +    Task.findByIdAndUpdate(id, { title, daysAllocated, daysRemaining, description, type, projectId }, { new: true })
`{new: true}`, should not be the case. Because we'll only update a task if it exists

2023-03-11 13:33 UTC, shubham-cpp commented on server/src/controllers/Task.ts
> +          error: 'Bad Request. Task with similar title already exists.',
IMO, this is not good idea, Two projects can have same task title. 
But I'm open to any points if you have?

2023-03-22 13:04 UTC, shubham-cpp commented
Hi sandy, been busy lately cause a lot of stuff, looks good to me.
Could you also add validations so we're good to merge

2023-03-24 15:46 UTC, isandeepkadam commented
Validation added, Let me know If I missed anything

2023-03-24 16:14 UTC, shubham-cpp commented on server/src/controllers/Task.ts
> +    .matches(/^[a-zA-Z0-9 ]*$/)
Use something like.
```js
.matches(/^[a-zA-Z]{3,}\s?[a-zA-Z0-9 ]+$/)
```
Since `[a-zA-Z0-9 ]*` regex also includes 11 111, as title which doesn't make sense. 
You can consider this as sanitization of input.

Also change this for updateTaskValidationSchema function

2023-03-24 16:14 UTC, shubham-cpp commented on server/src/controllers/Task.ts
> +  body('daysRemaining').optional().isDate().withMessage('Days remaining must be a date'),
condition for `daysRemaining` to be always greater than `daysAllocated`.
same for `updateValidationSchema`

2023-03-24 16:14 UTC, shubham-cpp commented on server/src/controllers/Task.ts
> +  body('currentOwner').notEmpty().withMessage('Current owner is required'),
`body('currentOwner').isMongoId()`

2023-03-25 04:54 UTC, isandeepkadam commented
Check now

2023-03-25 04:56 UTC, shubham-cpp commented
Everything thing looks good, I'll add some changes of my own this afternoon then Merge this. I'll also start working on **Projects** route 
https://lh3.google.com/u/0/d/19IFVkgzT4UcDi7x69H75T9a0xtcxtjlx=w526-h395-p-k-nu-iv1

2023-03-25 10:06 UTC, merged

2023-03-25 10:06 UTC, shubham-cpp commented
Just a TODO: we need to eventually move all the custom validations to `utils/validations` so we don't repeat ourselves