Modal comp
shubham-cpp/astro-project-manager pull request #8
Opened 2023-04-16 15:31 UTC by isandeepkadam

2023-04-19 14:17 UTC, shubham-cpp commented on client/src/components/Buttons.tsx
> +export const PrimaryButton: Component<{
**PrimaryButton** and **SecondaryButton**?.

Why not `<Button variant="secondary" />`
Default variant would be **primary**.
Also the default `type` of button should be `type="button"`. I dont know why the default type="submit".
[Mdn Docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#type)

2023-04-19 14:17 UTC, shubham-cpp commented on client/src/components/Modal.tsx
> +          <button onClick={() => setShow(false)}>❌</button>  {/** using Emoji for now */}
Use Astro icons, instead of emoji

2023-04-19 16:13 UTC, shubham-cpp commented on client/src/components/Modal.tsx
> +    <div class="modal-wrapper bg-slate-900 bg-opacity-70 z-50 fixed h-screen w-screen top-0 left-0 flex justify-center items-center">
Why not native [Dialog](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog). Its built-in with html. Also seems to have good support [check here](https://caniuse.com/?search=dialog)

2023-04-30 03:29 UTC, isandeepkadam commented
@shubham-cpp  bruhh

2023-04-30 17:06 UTC, shubham-cpp requested changes
Modal looks good

2023-04-30 17:06 UTC, shubham-cpp commented on client/src/components/Inputs/SelectInput.tsx
> +  options: string[]
make `options`, a `string[]` or array of `Option[]`
```typescript
type Option {
  value: string;
  label: string;
}
``` 

### Why?
Consider following scenario.
I want to select project from list, now we're stored project names as INT or ids,etc but we want the label of option to show Integration, Oracle Database or whatever actual name of project is.

2023-04-30 17:06 UTC, shubham-cpp commented on client/src/components/Inputs/SelectInput.tsx
> +          <option value={option} id={`${index}-${option}`}>
if we're not using `id` we can remove it

2023-04-30 17:06 UTC, shubham-cpp commented on client/tsconfig.json
> +    "allowImportingTsExtensions": true,
could you mention reasons behind this?

2023-05-05 14:09 UTC, isandeepkadam commented
@shubham-cpp changes done

2023-05-07 04:00 UTC, merged